language: ruby
cache: bundler
script: bundle exec rspec
dist: xenial
sudo: false

gemfile:
  - gemfiles/rack_1.5.gemfile
  - gemfiles/rack_1.6.gemfile
  - gemfiles/rack_2.0.gemfile

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1
